### ISSUE TITLE
Extension icons are without colour

### ISSUE THREAD

**Issue by iMonZ** [ideaweb/firefox-safari-style#38]
The extension icons in the top bar are without colour. https://ibb.co/P5LYW8L
Is there a way to change that?

**Comment by radiolevity** [comment]
I had assumed this is intended behavior since Safari does this. I like colorful icons, too, though. Put this in your userChrome.css somewhere after the firefox-safari-style `@import` line:

```css
.toolbarbutton-icon { filter: none !important; }
```
