### ISSUE TITLE
Auto hide tabs when there is only one

### ISSUE THREAD

**Issue by munro** [ideaweb/firefox-safari-style#63]
Is it possible to auto hide the tabs bar if there is only 1 tab?

Here's what I see in firefox:

![Screenshot 2025-01-02 at 10 50 16 AM](https://github.com/user-attachments/assets/cd9a7eb9-2438-4161-86b3-fbb35d343629)

And here's safari (it hides the tab bar)

![Screenshot 2025-01-02 at 10 47 17 AM](https://github.com/user-attachments/assets/965bb9a6-a9ba-4719-b5bf-5c9f8d3e30f6)

This probably isn't helpful, but I had also tried this minimal Firefox theme which says it autohides tab bar—but it didn't work for me: https://gist.github.com/morrolinux/87aa37396432ea5d14a9220bc4892100

**Comment by munro** [comment]
Hmmm, I hadn't use the install script, but it's still not working!

I also copied the code

```css
#alltabs-button,
#tabbrowser-tabs tab[first-visible-tab="true"][last-visible-tab="true"]:not([pinned]),
#tabbrowser-tabs tab[first-visible-tab="true"][last-visible-tab="true"]:not([pinned]) ~ toolbarbutton,
#tabbrowser-tabs tab[first-visible-tab="true"][last-visible-tab="true"]:not([pinned]) ~ #tabbrowser-arrowscrollbox-periphery {
  visibility: collapse;
}
```

https://github.com/ideaweb/firefox-safari-style?tab=readme-ov-file#hide-solo-tab

and it's still not working 😢 

![image](https://github.com/user-attachments/assets/29a35386-2ad3-4021-b4ce-97203e245a8d)
