### ISSUE TITLE
Hide horizontal tabs, bring back favicons on the bookmarks toolbar

### ISSUE THREAD

**Issue by Anakros** [ideaweb/firefox-safari-style#8]
You can hide horizontal tabs completely (to display tabs in a tree using addons) with this theme using the following styles in your userChrome.css
```css
#TabsToolbar {
  visibility:collapse;
}

#navigator-toolbox #titlebar {
  height: 0px !important;
  min-height: 0px !important;
  max-height: 0px !important;
}
```

You can bring back favicons of your bookmarks on the bookmarks toolbar using this:
```css
#navigator-toolbox #PersonalToolbar #personal-bookmarks #PlacesToolbarItems .bookmark-item .toolbarbutton-icon {
  display: inline !important;
}
```

Hopefully someone will find this useful :)
